#!/usr/bin/env python3

import argparse
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
BUILD_DIR = REPO_ROOT / "build"


def parse_hex(value):
    if isinstance(value, int):
        return value

    if isinstance(value, str):
        return int(value, 16)

    raise ValueError(f"Cannot parse value as hex/int: {value}")


def priv_to_sv(priv):
    priv_l = priv.lower()

    if priv_l == "user":
        return "PRIV_USER"

    if priv_l == "secure":
        return "PRIV_SECURE"

    raise ValueError(f"Unknown privilege level: {priv}")


def op_to_sv(entry, index):
    op = entry["op"].lower()
    addr = parse_hex(entry["addr"])
    priv = priv_to_sv(entry["priv"])

    comment = entry.get("comment", f"trace op {index}")

    lines = []
    lines.append(f'    $display("\\n[TRACE {index}] {comment}");')

    if op == "write":
        data = parse_hex(entry["data"])
        expected_error = int(entry.get("expected_error", 0))

        lines.append(
            f"    mmio_write(8'h{addr:02X}, 32'h{data:08X}, {priv}, 1'b{expected_error});"
        )

    elif op == "read":
        expected_rdata = parse_hex(entry.get("expected_rdata", "0x00000000"))
        expected_error = int(entry.get("expected_error", 0))

        lines.append(
            f"    mmio_read(8'h{addr:02X}, {priv}, 32'h{expected_rdata:08X}, 1'b{expected_error});"
        )

    else:
        raise ValueError(f"Unknown operation: {op}")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Convert a JSON MMIO trace into a SystemVerilog include file."
    )

    parser.add_argument(
        "trace_json",
        type=Path,
        help="Path to input JSON trace file.",
    )

    parser.add_argument(
        "--out",
        type=Path,
        default=BUILD_DIR / "generated_trace.svh",
        help="Output SystemVerilog include file.",
    )

    args = parser.parse_args()

    trace_path = args.trace_json
    out_path = args.out

    if not trace_path.exists():
        raise FileNotFoundError(f"Trace file does not exist: {trace_path}")

    BUILD_DIR.mkdir(exist_ok=True)

    with trace_path.open("r", encoding="utf-8") as f:
        trace = json.load(f)

    if not isinstance(trace, list):
        raise ValueError("Trace JSON must be a list of operations.")

    sv_ops = []

    for idx, entry in enumerate(trace):
        sv_ops.append(op_to_sv(entry, idx))

    output = "\n".join(
        [
            "// Auto-generated from JSON trace.",
            "// Do not edit this file directly.",
            "",
            *sv_ops,
            "",
        ]
    )

    out_path.write_text(output, encoding="utf-8")

    print(f"[DONE] Wrote generated trace to {out_path}")


if __name__ == "__main__":
    main()